### ISSUE TITLE
how about modify the syntax like this

### ISSUE THREAD

**Issue by sgf** [gammasoft71/xtd_properties#1]
```C++
property_<int> Number 
prop_<int> Number 

property_<int, readonly_> Number 
prop_get<int> Number or/ prop_readonly<int> Number 

property_<int, writeonly_> Number
prop_set<int> Number or/ prop_writeonly<int> Number 
```

**Comment by gammasoft71** [comment]
You can like this :

template<typename type_t>
using property_read_only_ = property_<type_t, readonly_>;

#define property_read_only_ property_read_only_

template<typename type_t>
using property_read_write_only_ = property_<type_t, writeonly_>;

#define property_read_write_only_ property_read_write_only_

**Comment by gammasoft71** [comment]
added :-)
