### ISSUE TITLE
Auto causes copy

### ISSUE THREAD

**Issue by bstordrup** [gammasoft71/xtd_properties#5]
We scan out code with Coverity on Polaris, and on this code

```
   property_ <std::string, readonly_> LastError {get_ { return m_lastError; }};
```

it reports a `Auto causes copy` because of the use of std::string. 

Some more details from Coverity on Polaris:
1. This lambda has an unspecified return type. This implies "auto" and causes the copy of an object of type "std::string".
2. Use "-> const auto &""std::string".
3. This return statement creates a copy.

Same thing is reported if I make a Coverity scan with Code Sight on the file containing the line.

Would the solution be to change the `get_` define to be

```
#define get_ \
  [&]()->const auto &
```

Because if I do the Coverity scan on the same file after changing the line to 

```
   property_ <std::string, readonly_> LastError {[&] ()->const auto& { return m_lastError; }};
```

Code Sight no longer reports the issue. But how would this change affect a `property_ <int>` ?

**Comment by bstordrup** [comment]
Tried copying the `Person` class example to a code file and scan it with Code Sight. It reports the `Auto causes copy` issue on the `Name` property, but not the `Age` property. So it seems to be only certain types affected.

So instead of changing the `#define get_`, it would perhaps be better to add a new 

```
  #define get_nocopy_ \
    [&]()->const auto&
```

for properties similar to `Name` property.

**Comment by gammasoft71** [comment]
Hi @bstordrup,
First off all thank you for your interest in properties.

You right, the param is copied when the property is get, I will fix this issue ASAP.

**Comment by gammasoft71** [comment]
Fixed in commit  https://github.com/gammasoft71/properties/commit/ef4d085534676c0844558e6ec5a8e912e934a65d

**Comment by bstordrup** [comment]
@gammasoft71, great! Will pull latest and update our code base with it.

Thank you
